config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  root 'weed#home'
  get '/products/new' => 'weed#new'
  post '/products' => 'weed#create'
  get '/products' => 'weed#index'
  get 'products/:id' => 'weed#show'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/products/:id' => 'weed#show'
  get '/listing/add' => 'listings#new'
  post '/listing/add' => 'listings#create'
  get '/listings' => 'listings#index'
  post '/listings' => 'listings#create'
  get '/listing/:id' => 'listings#show'
  resources :users
  resources :listings
  resources :weeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates(:username, presence: true, length: { maximum: 50 })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false})
  has_secure_password
  validates(:password, presence: true, length: { minimum: 6 })

  #Returns hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
end

app/models/weed.rb
class Weed < ApplicationRecord

  validates :name, :price, presence: true

  def self.search(search)
    where("name ILIKE ? OR strain ILIKE ? OR species ILIKE ?", "%#{search}", "%#{search}", "%#{search}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(permit_listing)
    if @listing.save
      flash[:success] = "Listing was successfully added."
      redirect_to listings_path
    else
      flash[:error] = @listing.errors.full_messages
      redirect_to listings_path
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  private

    def permit_listing
      params.require(:listing).permit(:image, :title, :price, :location,
      :zipcode, :body, :contact)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #Shows all Weed products
  def index
  end

  #Display one product
  def show
    @user = User.find(params[:id])
  end

  #Display form to add new product
  def new
    @user = User.new 
  end

  #Action to add product
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Weedmazon!"
      redirect_to @user
    else
      render 'new'
    end
  end

  #Display form to edit product
  def edit
  end

  #Action to edit product
  def update
  end

  #Action to destroy current product
  def destroy
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/weed_controller.rb
class WeedController < ApplicationController

  def home
    @weeds = Weed.all
  end

  #Shows all Weed products
  def index
    @weeds = Weed.all.order("created_at DESC")
  end

  #Display one product
  def show
    @weed = Weed.find(params[:id])
  end

  #Display form to add new product
  def new
    @weed = Weed.new
  end

  #Action to add product
  def create
    @weed = Weed.new(permit_products)
    if @weed.save
      flash[:success] = "Listing was successfully added."
      redirect_to index
    else
      flash[:error] = @weed.errors.full_messages
      redirect_to index
    end
  end

  #Display form to edit product
  def edit
  end

  #Action to edit product
  def update
  end

  #Action to destroy current product
  def destroy
  end

  private

    def permit_products
      params.require(:weed).permit(:image, :title, :name, :strain,
        :price, :species)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Login the given user
  def log_in user
    session[:user_id] = user.id
  end

  #Return the current logged in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  #Logs out the current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weed_helper.rb
module WeedHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact" %></li>
      <li><%= link_to "FAQ" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="center-align">
      <img id="logo" src="assets/kalyxlogo.png" />
    </div>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Add Products", "/products/new" %></li>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Signup", signup_path %></li>
        <li><%= link_to "Add Listing", listing_add_path %></li>
        <li><%= link_to "View Listings", listings_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_search_form.html.erb
<div class="search-form">
    <%= form_tag(products_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "What are you looking for?" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>

    <% if @weeds.blank? %>
      <h4>There are no products containing <%= params[:search] %>.</h4>
    <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kalyx</title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
<body id="body">
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
</body>
</html>

app/views/listings/index.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>City</th>
        <th>Description</th>
        <th>Posted</th>
      </tr>
    </thead>
  </table>
</div>
<% @listings.each do |t| %>
<div class="table-responsive">
<table class="table table-hover table-striped">
<tbody>
      <td>
        <%= link_to t.title, "/listing/#{t.id}" %>
      </td>
      <td>
        Price: <%= t.price %>
      </td>
      <td>
        City: <%= t.location %>
      </td>
      <td>
        Description: <br />
        <%= t.body %>
      </td>
      <td>
        <%= time_ago_in_words(Time.now) %>
      </td>
</tbody>
  </table>
</div>
<% end %>

app/views/listings/new.html.erb
<h1>Create A Listing</h1>

<div class="container-fluid">

  <%= form_for @listing, html: { multipart: true } do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>

    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>

    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: 'form-control' %>

    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control' %>

    <%= f.label :contact %>
    <%= f.text_field :contact, class: 'form-control' %>

    <%= f.submit "Create Listing", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/listings/show.html.erb
<div>
  <h1><%= @listing.title %></h1>
  <p>Price: <%= @listing.price %></p>
  <p>Location: <%= @listing.location %></p>
  <p>Zip Code: <%= @listing.zipcode %></p>
  <div>Description: <%= @listing.body %></div>
  <p>Contact: <%= @listing.contact %></p>
</div>

<div>
   <%= image_tag @listing.image.url %>
</div>

<div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: 34.052235, lng: -118.243683};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDppilg0C6Pn-tR7yGRxaTe49T9krqLtYE&callback=initMap">
    </script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/users/new.html.erb
<h1>Signup</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for User.new do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.username %>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>

app/views/weed/home.html.erb
<div class="search-form container-fluid row">
    <%= form_tag(products_path, :method => "get", id: "search-form") do %>

  <div>
<%= text_field_tag :search, params[:search], placeholder: "Search for...", class:"form-control" %>
  </div>
<div>
  <%= submit_tag "Search", :name => nil, class:"btn btn-primary" %>
</div>
    <% end %>

    <!-- <% if @weeds.blank? %>
      <h4>There are no products containing <%= params[:search] %>.</h4>
    <% end %> -->
</div>

<!-- <div class="row">
  <% @weeds.each do |t| %>
    <div class="col-4">
      <%= t.name %>
      <%= t.species %>
      <%= t.price %>
    </div>
  <% end %>
</div> -->

app/views/weed/index.html.erb
<div class="container">
  <div class="row">
    <% @weeds.each do |t| %>
      <div class="box col-3">
        <a href="#"><img src="assets/whitewidow.jpg"</a>
        <p><%= t.name %></p>
        <p><%= t.price %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/weed/new.html.erb
<h1>Add A Strain</h1>

<div class="container-fluid">

  <%= form_for @weed do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :strain %>
    <%= f.text_field :strain, class: 'form-control' %>

    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>

    <%= f.label :species %>
    <%= f.text_field :species, class: 'form-control' %>

    <%= f.submit "Add Strain", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/weed/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="weed_info">
      <h1>
        <%= @weed.name %> <br />
        <%= @weed.species %> <br />
        <p>Price: <%= @weed.price %></p>
<%= link_to @weed, products_path(:id) %>
      </h1>
    </section>
  </aside>
</div>